* SQL Crash Course - Introduction

** The Relational Model

*** A Brief Example

In 1970, Dr. E. F. Codd of IBM's research published a papel titled "A Relational
Model of Data for Large Shared Data Banks" that proposed that data be
represented as sets of /tables/. The following example represent how to
represent some client's bank accounts.

|-------------+------------+-----------|
| Customer ID | First Name | Last Name |
|-------------+------------+-----------|
|           1 | George     | Blake     |
|           2 | Sue        | Smith     |
|-------------+------------+-----------|

|------------+----------------|
| Product ID | Name           |
|------------+----------------|
| CHK        | Checking       |
| SAV        | Savings        |
| MM         | Money market   |
| LOC        | Line of Credit |
|------------+----------------|

|------------+------------+-------------+---------|
| Account ID | Product ID | Customer ID | Balance |
|------------+------------+-------------+---------|
|        103 | CHK        |           1 | $75.00  |
|        104 | SAV        |           1 | $250.00 |
|        105 | CHK        |           2 | $783.00 |
|        106 | MM         |           2 | $500.00 |
|        107 | LOC        |           2 | $0.00   |
|------------+------------+-------------+---------|

|----------------+------------------+------------+----------+------------|
| Transaction ID | Transaction Type | Account ID | Amount   |       Date |
|----------------+------------------+------------+----------+------------|
|            978 | DBT              |        103 | $100.00  | 2004-01-22 |
|            979 | CDT              |        103 | $25.00   | 2004-02-05 |
|            980 | DBT              |        104 | $250.00  | 2004-03-09 |
|            981 | DBT              |        105 | $1000.00 | 2004-03-25 |
|----------------+------------------+------------+----------+------------|

Each table in a relational database includes information that uniquely
identifies a row in that table (known as the *primary key*), along with
additional information needed to describe the entity completely. In the previous
example, at the Customer Table, the /Customer ID/ column holds a different
number for each customer. No other customer will ever be assigned the same
identifier as other customer.

*** Terminology

An *entity* is something of interest to the database. In the previous example,
this included customers, products, transactions, etc. A *column* is an
individual piece of data stored in a table which is related to an entity. A
*row* is a set of columns that together completely describe an entity or some
action on an entity; it is also known as a *record*. A *table* is a set of rows,
held either in memory (nonpersistent) or on a permanent state (persistent). The
*result set* is another name for a /nonpersistent table/, generally the result
of an SQL query. The *primary key* is the unique identifier for each row in the
table, it can consist of one or more columns. Finally a *foreign key* is an
identifier to locate a row on another table, it can consist of one or more
columns.

** What is SQL?

SQL is basically a language for manipulating the data found in relational
tables.

*** SQL Statements

The SQL language is divided into several distinct parts: the *SQL schema
statements*, which are used to define the data structures stored in the
database; *SQL statements*, which are used to manipulate the data structures
previously defined; and *SQL transaction statements*, which are used to begin,
end and roll back transactions. For example, to create a new table in your
database, you would use the SQL schema statement ~create table~, whereas the
process of populating your new table with data would require the SQL data
statement ~insert~.

Here's an example of an SQL schema statement to create a table called
~corporation~.

#+begin_src sql
      CREATE TABLE corporation
             (corp_id SMALLINT,
             name VARCHAR(30),
             CONSTRAINT pk_corporation PRIMARY KEY (corp_id));
#+end_src

The previous statement creates a table with two columns, ~corp_id~ and ~name~,
with the first column being the primary key for the rows of the table. Now
here's an SQL statement to insert a row into the ~corporation~ table.

#+begin_src sql
  INSERT INTO corporation (corp_id, name)
  VALUES (27, 'Acme Paper Corporation');
#+end_src

This statement adds a row to the corporation table with a value of ~27~ for the
~corp_id~ column and a value of ~Acme Paper Corporation~ for the name column.

Finally, here's a simple ~select~ statement to retrieve the data that was just
created.

#+begin_src sql
  SELECT name FROM corporation WHERE corp_id = 27;
#+end_src

Executing the previous statement returns the following table:

|------------------------|
| name                   |
|------------------------|
| Acme Paper Corporation |
|------------------------|


*** SQL Data Types

In general, all popular database servers have the capacity to store the same
types of data, such as strings, dates, and numbers. Where they typically differ
is in the specialty data types, such as XML and JSON documents or spatial data.
For these notes we will be exploring ~MySQL~ data types, in this case the
character, date, and numeric data types.

**** Character Data

The character data can be stored as either fixed-length or variable-length
strings; the difference is that fixed length strings are right-padded with
spaces and always consume the same number of bytes, and variable length strings
are not right-padded with spaces and don't always consume the number of bytes.

When defining a character column, you must specify the maximum size of any
string to be stored in the column. For example, if you want to store strings up
to 20 characters in length, you could use either of the following definitions:

#+begin_src sql
  char(20)    /* fixed-length */
  varchar(20) /* variable-length */
#+end_src

The maximum length for a ~char~ column is currently 255 bytes, whereas ~varchar~
columns can be up to 65,535 bytes.

**** Text data

If you need to store longer strings that might exceed the 64KB limit for
~varchar~ columns (such as emails, XML documents, etc.), then you will want to
use one of the text types.

|--------------+-------------------------|
| Text type    | Maximum number of bytes |
|--------------+-------------------------|
| ~tinytext~   | 255                     |
| ~text~       | 65,535                  |
| ~mediumtext~ | 16,777,215              |
| ~longtext~   | 4,294,967,295           |
|--------------+-------------------------|

There are some considerations to be taken when using the previous data types:

- If the data exceeds the maximum size of the type, the data will be truncated.
  
- Trailing spaces will not be removed when data is loaded into the column.
  
- When sorting this data types, only the first 1024 bytes are considered, this
  limit can be changed.

- MySQL has different text types. SQL Server has a single ~text~ type for large
  character data, whereas DB2 and Oracle use a data type called ~clob~ for
  /Character Large Object/.

**** Numeric Data

The numeric data, contrary to popular opinion, may represent several things. For
example, boolean types, a system-generated primary key for a transaction table,
the amount of items in a shopping basket, or positional data, they may all be
numeric data but they represent different things.

To handle these data types, MySQL has several different numeric data types. the
most commonly used numeric types are those used to store whole numbers, or
/integers/. When specifying one of these types, you may also specify that the
data is /unsigned/, which tells the server that all data stored in the column
will be greater than or equal to zero.

|-------------+---------------------------------+--------------------|
| Type        | Signed Range                    | Unsigned Range     |
|-------------+---------------------------------+--------------------|
| ~tinyint~   | -128 to 127                     | 0 to 255           |
| ~smallint~  | -32,768 to 32,767               | 0 to 65,535        |
| ~mediumint~ | −8,388,608 to 8,388,607         | 0 to 16,777,215    |
| ~int~       | −2,147,483,648 to 2,147,483,647 | 0 to 4,294,967,295 |
| ~bigint~    | −2^63 to 2^63 - 1               | 0 to 2^64 - 1      |
|-------------+---------------------------------+--------------------|

Given an integer type, MySQL allocates an appropriate amount of space to store
the data. There are also data types for floating numbers like ~float(p, s)~ and
~double(p, s)~ where ~p~ is the number of digits the number before the decimal
point has, and ~s~ is the number of digits the number of digits the number after
the decimal point has. For example, ~float(4, 2)~ will be able to store numbers
like 27.44 and 8.19, but the number 17.8675 would be rounded to 17.87, and the
number 178.375 will return an error.

**** Temporal Data

When working with dates and/or times, this data in SQL is referred as
/temporal/.  For example, a future date for a particular date, the date a
customer's order was shipped, the date and time that user modified a particular
row in a table, or an employer's birth date, they're all considered as /temporal
data/.

The following temporal data are supported by MySQL

|-------------+---------------------+------------------------------------------------------|
| Type        | Default format      | Allowable values                                     |
|-------------+---------------------+------------------------------------------------------|
| ~date~      | YYYY-MM-DD          | 1000-01-01 to 9999-12-31                             |
| ~datetime~  | YYYY-MM-DD HH:MM:SS | 1000-01-01 00:00:00.0000 to 9999-12-31 23:59:59.9999 |
| ~timestamp~ | YYYY-MM-DD HH:MM:SS | 1000-01-01 00:00:00.0000 to 2038-01-18 22:14:07.9999 |
| ~year~      | YYYY                | 1901 to 2155                                         |
| ~time~      | HHH:MM:SS           | -838:59:59.0000 to 838:59:59.0000                    |
|-------------+---------------------+------------------------------------------------------|


*** SQL Schema Statements

**** Table Creation

As we've mentioned before the ~CREATE~ statement is for creating a table,
generally creating a table means defining the attributes (columns) that are
related to an entity (rows). For example, the following statement creates a
table to hold information about people:

#+begin_src sql
  CREATE TABLE person       
      (person_id SMALLINT UNSIGNED,
      fname VARCHAR(20),
      lname VARCHAR(20),
      eye_color CHAR(2),
      birth_date DATE,
      CONSTRAINT pk_person PRIMARY KEY (person_id)
      );
#+end_src

***** Check Constraints

There a different types of constraints. One, for example, is the *primary key
constraint*, in which we define what column or columns will be considered as the
primary key for the table. Another type of constraint is called *check
constraints* which limits the possibles values for that particular column. MySQL
allows a check constraint to be attached to a column definition, as in the
following:

#+begin_src sql
          eye_color CHAR(2) CHECK (eye_color in ('BR', 'BL', 'GR')),
#+end_src

One small detail is that MySQL allows check constraints but does not enforce
them, to enforce them we must use a data type called ~enum~ that merges the
check constraint into a data type definition. Here's what the definition would
look like:

#+begin_src sql
          eye_color ENUM('BR', 'BL', 'GR'),
#+end_src

***** Describing a table

If you want to make sure a table exists, you can use the ~describe~ command to
look at the table definition.

***** What is a NULL value?

In some cases, it is not possible or applicable to provide a value for a
particular column in your table. For example, when adding data about a new
customer order, the ~ship_date~ column can't yet be determined. In this case,
the column is said to be /null/, which indicates the absence of a value.

When designing a table, you may specify which columns are allowed to be null and
which columns are not allowed to be null by adding the keyword ~not null~ after
the type definition. For example:

#+begin_src sql
  CREATE TABLE person       
      (person_id SMALLINT UNSIGNED NOT NULL,
      fname VARCHAR(20) NOT NULL,
      lname VARCHAR(20) NOT NULL,
      eye_color CHAR(2),
      birth_date DATE NOT NULL,
      CONSTRAINT pk_person PRIMARY KEY (person_id)
      );
#+end_src

***** Foreign Keys

If the value of a column references another value in another table then we say
that said value is a foreign key. For example if we define the following table:

#+begin_src sql
  CREATE TABLE favorite_food
         (person_id SMALLINT UNSIGNED,
         food VARCHAR(20),
         CONSTRAINT pk_favorite_food PRIMARY KEY (person_id, food),
         CONSTRAINT fk_fav_food_person_id FOREIGN KEY (person_id)
         REFERENCES person (person_id)
         );
#+end_src

Another type of constraint is the *foreign key constraint*. This constraints the
values of the column in the table to only include the values found on the
specified column of the referencing table; for example the ~person_id~ column in
the ~favorite_food~ table includes only values found in the ~person_id~ column
of the ~person~ table.

**** Populating and Modifying Tables
***** Inserting Data

Let's continue with our example of ~person~ and ~favorite_food~ tables.  To
insert data into any table we must use the ~insert~ statement, which consists of
three main components:

+ The name of the table into which to add the data
+ The names of the columns in the table to be populated.
+ The values with which to populate the columns.

As we've seen before, some values can be null and some other can't. Thus it's
not necessary to include all columns when inserting data into a table; except if
all columns can't be null. Thus the following statement creates a row in the
~person~ table for William Turner:

#+begin_src sql
  INSERT INTO person
         (person_id, fname, lname, eye_color, birth_date)
         VALUES (null, 'William', 'Turner', null, '1972-05-27');
#+end_src

****** Generating Primary Keys

Now, before adding data into our table its good to consider how to generate the
value related to a primary key in the table. We could look at the largest value
currently in the table and add one, or we can let the database server provide
the value for us. The latter is the safest option. All database servers today
provide an efficient way of generating number keys. For example, Oracle Database
has a separate schema object known as /sequence/; in the case of MySQL we only
need to turn on the ~auto-increment~ feature for the primary key column.

#+begin_src sql
  person_id SMALLINT UNSIGNED AUTO_INCREMENT,
#+end_src


***** Updating Data

Let's say that at the moment of creation we didn't know the eye color of
William, but now we know that he has green eyes. We need to modify the row that
corresponds to William and to do so we use the ~update~ statement. For the
previous example, the following statement is required:

#+begin_src sql
  UPDATE person
  SET eye_color = 'GR' WHERE fname = 'William' AND lname = 'Turner';
#+end_src

In this case the ~where~ clause helps us to modify only the tables we're
interested in.

***** Deleting Data

When needing to delete certain information or data of a table the statement
~delete~ is used. For example, if for some reason William never existed, then
the statement to remove William from the ~person~ table is:

#+begin_src sql
  DELETE FROM person WHERE fname = 'William' AND lname = 'Turner';
#+end_src
